task_DEV-1
TatianaGantievskaya/TAT_2018 pull request #1
Opened 2018-03-02 14:28 UTC by TatianaGantievskaya

2018-03-02 15:30 UTC, AlexanderSoroka requested changes

2018-03-02 15:30 UTC, AlexanderSoroka commented on TheLongestSubsequence/Properties/AssemblyInfo.cs
> +// Общие сведения об этой сборке предоставляются следующим набором
Do not use russian in production

2018-03-02 15:30 UTC, AlexanderSoroka commented on TheLongestSubsequence/Sequence.cs
> +      int theLongestSubsequence = FindTheLongestSubsequence();
single responsibility violation

2018-03-03 11:10 UTC, AlexanderSoroka requested changes

2018-03-03 11:10 UTC, AlexanderSoroka commented on TheLongestSubsequence/Sequence.cs
> +    protected int FindTheLongestSubsequence()
why it's protected?

2018-03-03 11:10 UTC, AlexanderSoroka commented on TheLongestSubsequence/Sequence.cs
> +    public void GetMaxAmountOfTheSameConsecutiveSymbols()
SOLID violation

2018-03-03 14:12 UTC, IgorKheidorov requested changes

2018-03-03 14:12 UTC, IgorKheidorov commented on TheLongestSubsequence/InformationOutput.cs
> +    /// </summary>
Method get can't prints anything

2018-03-03 14:12 UTC, IgorKheidorov commented on TheLongestSubsequence/Sequence.cs
> +    /// <summary>
same == iidentical

2018-03-03 14:12 UTC, IgorKheidorov commented on TheLongestSubsequence/Sequence.cs
> +        }
How its can be happened i.Equals(EnteredSequence.Length - 2

2018-03-03 14:12 UTC, IgorKheidorov commented on TheLongestSubsequence/Sequence.cs
> +    /// <returns> It returns the value, which reflects the maximum length of the subsequence. </returns>
Better :  maximum of identical subsequence  length

2018-03-03 18:57 UTC, AlexanderSoroka approved these changes
Over-complicated solution

2018-03-04 11:01 UTC, merged