task_DEV-3
TatianaGantievskaya/TAT_2018 pull request #5
Opened 2018-03-06 18:47 UTC by TatianaGantievskaya

2018-03-06 19:19 UTC, IgorKheidorov requested changes
Too original decision, try to simplify

2018-03-06 19:19 UTC, IgorKheidorov commented on NumberConverter/Converter.cs
> +    private Int16 radix;
no need to store radix in Int16 format

2018-03-06 19:19 UTC, IgorKheidorov commented on NumberConverter/ConvertingException.cs
> +  /// <summary>
No need to select new type of exception

2018-03-06 19:19 UTC, IgorKheidorov commented on NumberConverter/EntryPoint.cs
> +      }
No need to process different types of exceptions which are processed in the same way

2018-03-06 19:19 UTC, IgorKheidorov commented on NumberConverter/EntryPoint.cs
> +        Converter convertibleNumber = new Converter(args[0], args[1]);
Very strange construction

2018-03-06 19:19 UTC, IgorKheidorov commented on NumberConverter/Converter.cs
> +        Int64 temporaryVariable = convertibleNumber / radix;
Too complicated and unclear method to find the necessary symbol, has to be simplified

2018-03-06 19:19 UTC, IgorKheidorov commented on NumberConverter/Converter.cs
> +    /// <summary>
Unclear comment

2018-03-07 11:12 UTC, AlexanderSoroka requested changes

2018-03-07 11:12 UTC, AlexanderSoroka commented on NumberConverter/Converter.cs
> +    private Int64 convertibleNumber;
Either use big integer either just int, int 64 has almost the same limitations as int

2018-03-07 11:12 UTC, AlexanderSoroka commented on NumberConverter/Converter.cs
> +    /// Constructor with the parameters, which initializes class's fields.
"Constructor with the parameters" - it's obvious from the code

2018-03-07 11:12 UTC, AlexanderSoroka commented on NumberConverter/Converter.cs
> +      if (radix < 2 || radix > 20 || convertibleNumber <= 0)
I would separate these checks

2018-03-08 19:29 UTC, AlexanderSoroka approved these changes

2018-03-08 19:29 UTC, AlexanderSoroka commented on NumberConverter/Converter.cs
> +      if (radix < 2 || radix > 20)
it's better to create custom setter

2018-03-08 19:29 UTC, AlexanderSoroka commented on NumberConverter/Converter.cs
> +    public char[] ConvertNumberToSelectedNumeralSystem()
return string instead of char[]

2018-03-08 19:29 UTC, AlexanderSoroka commented on NumberConverter/Converter.cs
> +          convertedNumber.Append((char)(calculatedVariable + 55));
why 55?

2018-03-16 15:02 UTC, merged